# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 308713082028b4df5c996bbb2afb085769c7d604e613005d24036bb25683d7d1d9363fd123d1209eb6b8c638a18b7e50bb35f3ed3d84234de159706fc22ceebd

test:
  secret_key_base: 88992c2cd3d97db7d5f9ff8eecd8b9a6c5bc51c9ccf42937077fc3955d4c03004520d21ee371c975f6d6cb3fdb70879b6dce704d398e79a51711dfb24d08e4ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 866f0d4eed2392dddfb64326a7eae4a9707a8f965358f2393bcdf9f26b56413013e1558f834c2f2a53bd84e3a81fe73ca74e895995a46a2a705e1756fed123a5
